language: node_js

node_js:
  - "6.0"

env:
  - CC=gcc-4.8 CXX=g++-4.8
  - CC=echo CXX=echo

install: npm install nbind && cd node_modules/nbind && npm install && cd ../.. && npm install

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
